title: Flip Clock Card Gallery
views:
  - title: Overview
    path: overview
    icon: mdi:star
    type: sidebar
    cards:
      - type: markdown
        content: |
          # ✈️ New Aviator Theme
          Inspired by classic airport departure boards. Uses 'Oswald' font.
      - type: custom:flip-clock-card
        theme: aviator
        show_seconds: true
        size: 100
        title: Aviator (Large)
      - type: grid
        columns: 2
        cards:
          - type: custom:flip-clock-card
            theme: aviator
            show_seconds: false
            size: 60
            title: Aviator (Compact)
          - type: custom:flip-clock-card
            theme: aviator
            show_seconds: true
            size: 60
            title: Aviator (Standard)
      - type: markdown
        content: |
          ### 🔥 Popular Picks
          Quick access to user favorites.
      - type: vertical-stack
        cards:
          - type: custom:flip-clock-card
            theme: ios-dark
            size: 50
            title: iOS Dark
          - type: custom:flip-clock-card
            theme: classic
            size: 50
            title: Classic
          - type: custom:flip-clock-card
            theme: neon
            size: 50
            title: Neon
  - title: All Themes
    path: themes
    icon: mdi:palette
    cards:
      - type: markdown
        content: '# 🎨 Theme Gallery'
      - square: true
        type: grid
        title: Modern & Clean
        columns: 4
        cards:
          - type: custom:flip-clock-card
            theme: classic
            title: Classic
          - type: custom:flip-clock-card
            theme: ios-light
            title: iOS Light
          - type: custom:flip-clock-card
            theme: ios-dark
            title: iOS Dark
          - type: custom:flip-clock-card
            theme: e-ink
            title: E-Ink
      - square: true
        type: grid
        title: Retro & Glow
        columns: 4
        cards:
          - type: custom:flip-clock-card
            theme: neon
            title: Neon
          - type: custom:flip-clock-card
            theme: synthwave
            title: Synthwave
          - type: custom:flip-clock-card
            theme: terminal
            title: Terminal
          - type: custom:flip-clock-card
            theme: red-stealth
            title: Red Stealth
      - square: true
        type: grid
        title: Natural & Sci-Fi
        columns: 4
        cards:
          - type: custom:flip-clock-card
            theme: wood
            title: Wood
          - type: custom:flip-clock-card
            theme: borg
            title: Borg
          - type: custom:flip-clock-card
            theme: trek-orange
            title: Trek Orange
          - type: custom:flip-clock-card
            theme: trek-blue
            title: Trek Blue
    type: sidebar
  - title: Configs
    path: configs
    icon: mdi:cog
    cards:
      - type: markdown
        content: '# ⚙️ Configuration Examples'
      - type: markdown
        content: '### Seconds: On vs Off'
      - square: true
        type: grid
        columns: 1
        cards:
          - type: custom:flip-clock-card
            theme: aviator
            show_seconds: true
            title: With Seconds
          - type: custom:flip-clock-card
            theme: aviator
            show_seconds: false
            title: Without Seconds
      - type: markdown
        content: '### Sizes: 40px to 120px'
      - type: grid
        columns: 1
        cards:
          - type: custom:flip-clock-card
            theme: classic
            size: 40
            show_seconds: false
            title: Tiny (40px)
          - type: custom:flip-clock-card
            theme: classic
            size: 80
            title: Standard (80px)
          - type: custom:flip-clock-card
            theme: classic
            size: 120
            title: Huge (120px)
    type: sidebar
  - title: Custom
    path: custom
    icon: mdi:brush
    cards:
      - type: markdown
        content: |
          # 🖌 Custom Styles
          Override themes using `custom_style`.
      - type: custom:flip-clock-card
        theme: classic
        size: 80
        title: Gold & Navy
        custom_style:
          bg: '#003366'
          text: '#ffcc00'
          radius: '0.2'
          shadow: 0 10px 20px rgba(0,0,0,0.5)
      - type: custom:flip-clock-card
        theme: classic
        size: 80
        title: Minimal White
        show_seconds: false
        custom_style:
          bg: '#ffffff'
          text: '#333'
          radius: '0'
          shadow: none
          line: '#eee'
    type: sidebar
